### ISSUE TITLE
Game keeps crashing whenever I try to start a game with mod 1.6

### ISSUE THREAD

**Issue by AXEL-M74** [captaincobbs/ESG-Mod#1200] opened 2022-05-15 16:58 UTC
I run this and two cosmetic mods:
Black Heroes
Grey Behemoths

The game doesn't crash with 1.5 and these mods, only with 1.6.
Here are the two logs from the most recent crash, from today.
[error.log](https://github.com/wakystuf/ESG-Mod/files/8695450/error.log)
[output_log.txt](https://github.com/wakystuf/ESG-Mod/files/8695451/output_log.txt)
 
Any other info I could provide here, let me know. I want to solve this.

**Comment by FluffiestPrincess** [comment] 2022-05-15 17:10
Hi Axel,

Can you let us know which DLCs you're running?

**Comment by ghost** [comment] 2022-05-15 17:13
All of them. 
Awakening, Penumbra, Vaulters, Supremacy for the major ones.
Dark Matter, Celestial Worlds, Digital Deluxe, Harmonic Memories, Lost Symphony, Untol Tales, Much & Makers, the Sophon hero and the Communtiy challenge add-on.
I also have the smaller ones from the G2G, like the Pug and such.

**Comment by FluffiestPrincess** [comment] 2022-05-15 17:17
Awesome, thank you. And you have them all enabled?

Can you post screenshots of the settings you use when starting a new game, and your graphics settings?

**Comment by ghost** [comment] 2022-05-15 17:24
Here you go, and yes, all of them are enabled but the Pug. Something weird seems to be going on with the memory use from what I've noticed, I checked my PC usage, and when the game generated, even with everything closed, it just gobbles up the RAM to 98%.
![Screenshot_1](https://user-images.githubusercontent.com/105115857/168485724-8b919814-1788-47ba-98d3-5d0335efc584.png)
![Screenshot_2](https://user-images.githubusercontent.com/105115857/168485728-d65ef360-a13d-4555-8b1b-03b28a1acc21.png)
![Screenshot_3](https://user-images.githubusercontent.com/105115857/168485730-032299f0-0820-494f-8ea4-2166df36c81d.png)
![Screenshot_4](https://user-images.githubusercontent.com/105115857/168485731-aebb6751-5632-4def-87a5-02e6de31251d.png)
![Screenshot_5](https://user-images.githubusercontent.com/105115857/168485732-d82240be-58ef-4b49-80d1-a0ba7c3e6da4.png)

**Comment by FluffiestPrincess** [comment] 2022-05-15 19:15
Ok, thank you. The crash dump does say "out of memory". How _much_ memory do you have, exactly? It'd be good to know how much it's eating, it gets up to 10GB for me on those settings but doesn't crash - that said, I don't have any of the DLC, so if the problem is with behemoths, I wouldn't see it.

**Comment by ghost** [comment] 2022-05-16 08:57
8 GB total. Generally 4.1 GB are in use when I start the game and it skyrockets as it tries to generate the world to the aforementioned value, 7.9 or so.

**Comment by captaincobbs** [comment] 2022-05-16 11:01
Ouch I'd really recommend upgrading, ES2 frequently goes up to 10 gb for me.

**Comment by ghost** [comment] 2022-05-16 11:22
An upgrade is planned for later this year, entirely new PC since this was budget in 2016 when I made it.

I guess I should stick with 1.5 in the meantime, since it doesn't cause this issue?

**Comment by captaincobbs** [comment] 2022-05-16 11:49
My guess is that 1.6 loads too many images?

**Comment by ghost** [comment] 2022-05-16 12:41
So I actually managed to start a game with 1.6 by closing everything running on the PC that's not essential. Here's some things I've found out.

Game capped at 7.6 GB used from 3.4 GB. The spike/top points of the RAM usage are when it says "Game Launched" and "Game Launched and Ready" steps of the loading screen.

After the game started, RAM usage started decreasing at a pretty decent rate to around 5.5 GB, after which I can open the browser and everything else I need without issue. I often use Terraformation charts and the Wiki to plan my heroes and the sort.

EDIT: Updated the values after a second test.

**Comment by FluffiestPrincess** [comment] 2022-05-17 11:34
Axel, can you start a game in 1.6 if you disable the "black heroes" and "grey behemoths" mods? If so, it seems pretty clear that the issue here is just the game loading too many textures and other large files.

**Comment by ghost** [comment] 2022-05-17 14:00
I did a test run as you asked. It actually happens to start, at a much lower use, around 6.8 GB peak to 6.2. It seems to vary, but I don't know the reason.

I find it odd though that it only happens with 1.6 but not 1.5 hence why I even decided to make this post in the first place.

With 1.5 it capped at around 7.2 with mods on. Could it be that some of the new world generation settings like balanced map generation add to the extra RAM use when creating a game?

**Comment by wakystuf** [comment] 2022-05-18 05:08
World generation is unlikely to be the issue, though it's not impossible. Adding 5k lines of code or whatever is still less RAM intensive, I think, than a couple of textures

**Comment by ghost** [comment] 2022-05-18 17:12
There seems to be some weird interaction going on, but given how weirdly specific is, I don't think it's even worth the time of the mod devs to try and find out the issue.

Should we close this? I don't know if it helps anybody besides a PSA for people with lower-end systems.

**Comment by FluffiestPrincess** [comment] 2022-05-21 20:31
Closing this one - it's essentially a memory usage issue, there's not a lot we can do about it.

**Closed as not planned by FluffiestPrincess** 2022-05-21 20:31 UTC
Labels: Rejected, ESG bug
