### ISSUE TITLE
Error while loading the mod

### ISSUE THREAD

**Issue by tuan1515** [captaincobbs/ESG-Mod#1474] opened 2024-04-15 03:11 UTC
[Diagnostics - 2024'04'15 @1005'33''.txt](https://github.com/wakystuf/ESG-Mod/files/14973527/Diagnostics.-.2024.04.15.%401005.33.txt)

**Comment by captaincobbs** [comment] 2024-04-15 22:16
I've investigated this more-- I genuinely don't understand what the issue is, no fault of yours. Are you using ESG 1.5? The line the crash error refers to is empty in 1.6.

**Comment by tuan1515** [comment] 2024-04-16 00:34
Are we talking about the same https://github.com/wakystuf/ESG-Mod/tree/Tat011-Tweaks, Tat011 updated PopulationDefinitions.xml, that error specifically refers to that. I hope the .txt was renamed to .html. I think Tat011 knows what I'm talking about, don't worry he'll fix it, once he comes back from the break. Not to say anything bad about Tat011, I genuinely appreciate that he is dedicating his time to this amazing game that has big potential, but wasn't so good deployed by the Amplitude devs

**Comment by Tat011** [comment] 2024-04-16 01:22
Tat011 tweaks is an in progress branch that has little testing at the moment, you should stick to the main 1.6 as its actually stable and this branch will eventually be merged with it. That being said if you find errors/crashes/bugs with this branch and report them its very much appreciated.

**Comment by tuan1515** [comment] 2024-04-16 04:53
No problem, I would like to stress how thankful I am for your work

**Comment by Tat011** [comment] 2024-04-16 11:54
> [Diagnostics - 2024'04'15 @1005'33''.txt](https://github.com/wakystuf/ESG-Mod/files/14973527/Diagnostics.-.2024.04.15.%401005.33.txt)

this crash should be fixed now

**Closed as completed** 2024-04-16 13:34 UTC
