### ISSUE TITLE
Bugs - 1.4 Testing

### ISSUE THREAD

**Issue by captaincobbs** [captaincobbs/ESG-Mod#570] opened 2021-05-29 21:36 UTC
New Deal doesn't provide any bonus whatsoever (Reported while playing Republic)
Filter Barges can't be built while in the construction queue of another system, and do not require strategic deposits on the system.

**Comment by Arpharnator** [comment] 2021-05-29 21:37
filters barges aren't unique, but you can only build 1 at a time

**Comment by captaincobbs** [comment] 2021-05-29 21:38
Corrected my comment

**Comment by wakystuf** [comment] 2021-05-29 22:27
Here's the problem for New Deal; I didn't update the path when I debugged it (it should go down to ColonizedStarSystem, as the regular version does):

    &lt;Modifier TargetProperty="SystemFIDSPercent" Operation="Addition" Value="$(LocalFIDSBonusDecaying_Republic)" Path="../ClassEmpire" TooltipHidden="true"/&gt;<br class="Apple-interchange-newline">

On the filter barges, I'm not certain how to fix that but I can try later this weekend.

**Comment by wakystuf** [comment] 2021-05-29 22:41
OK, I think this line is the problem for Filter Barges:
InterpreterPrerequisite Inverted="true" Flags="Prerequisite,Discard"&gt;Path(Context,@'../ClassEmpire/ClassStarSystem,BuildingStarSystemImprovementUniqueStrategicVaulters') and not(Path(Context,@'ClassStarSystem,BuildingStarSystemImprovementUniqueStrategicVaulters'))&lt;/InterpreterPrerequisite&gt;<br class="Apple-interchange-newline">

**Comment by captaincobbs** [comment] 2021-05-29 22:56
Fixed Filter Barges and the New Deal

**Comment by wakystuf** [comment] 2021-05-30 01:47
Sounds like other guys have also found these bugs (let me know if I missed any):
1) Vaulters getting Free Move too early (need to confirm this is Vaulter-specific)
2) Need to offset RB and Craver food incrementation for their outposts
3) Space ports showing too many slots for Vaulters on SD2
4) Curiosity droplists may have reverted to vanilla (pirates, bad battle tactics, etc)?

For 2) above I already know what is going on and will fix it in a day or 2 when I have time. For the others I have no idea, but I can look into them if nobody else has any idea either. Sounded like Cobbs might have some sense of 1) and 4)?

**Comment by wakystuf** [comment] 2021-05-30 07:39
Some other bugs I just found in a playthrough with some friends:
1) Sci Happy law giving far more happiness than expected (I will investigate)
2) I was getting double flat FIDSI bonuses from SD2 (both the +10 FIDSI and the "from system development")
![image](https://user-images.githubusercontent.com/79942510/120096158-d5b81c00-c0f7-11eb-8953-2e054bd5b3bc.png)

**Comment by wakystuf** [comment] 2021-05-31 00:24
Some of these are now fixed. I believe @captaincobbs  fixed the curiosity droplists, and I've just fixed the duplication of SD effects (btw @Doruk-Coskun  I think this is what was causing your issue with too many spaceport slots but lmk if that still happens).

**Comment by wakystuf** [comment] 2021-05-31 01:40
These are the ones that are still left to fix:
* Vaulters getting Free Move too early (need to confirm this is Vaulter-specific?)
* Need to offset RB and Craver food incrementation for their outposts
* Sci law may be providing too much happiness? I cannot replicate this issue but have heard of it

**Comment by wakystuf** [comment] 2021-06-02 04:42
OK, these should now be all set except for this one: @Doruk-Coskun  can you clarify what the issue was that you were reporting here?
Vaulters getting Free Move too early (need to confirm this is Vaulter-specific?)

**Comment by Doruk-Coskun** [comment] 2021-06-02 07:06
Free move upgrade tech provides unupgraded free move if the free move tech is not researched. I believe its the same bug we encountered with the wormhole bug we encountered with riftborn pop collection 3. We need to change the upgraded free move to be a parameter multiplier rather than an addition.

**Comment by Doruk-Coskun** [comment] 2021-06-02 07:08
> Some of these are now fixed. I believe @captaincobbs fixed the curiosity droplists, and I've just fixed the duplication of SD effects (btw @Doruk-Coskun I think this is what was causing your issue with too many spaceport slots but lmk if that still happens).

Its confirmed that SDs don't give extra pop move slots anymore

**Comment by Doruk-Coskun** [comment] 2021-06-02 11:24
Pop boosting with luxury doesn't work, confirmed.

**Comment by Doruk-Coskun** [comment] 2021-06-02 12:00
Ive just noticed with the Recent push of waky's, vaulter explorer sslotss have changed but since the ShipDesignDefinitions have not the explorer ship starts with 2 explorer module still (a remnant invisible module which can not be edited.)

**Comment by wakystuf** [comment] 2021-06-02 15:59
Oh, good point on the Vaulter scout hull. I don't know how to fix that though; do you?

**Comment by Doruk-Coskun** [comment] 2021-06-02 16:52
I do, no worries

**Comment by wakystuf** [comment] 2021-06-02 17:51
@captaincobbs @Doruk-Coskun pulling all of these bugs into one place. I don't know how to fix any of these, so I'm hoping that you guys do...

* Pop boosting with luxury doesn't work
* Free move upgrade tech provides unupgraded free move if the free move tech is not researched. I believe its the same bug
with the wormhole bug we encountered with riftborn pop collection 3. We need to change the upgraded free move to be a parameter multiplier rather than an addition.
* Fix Vaulter scout hull having a remnant invisible module from my previous push

**Comment by Doruk-Coskun** [comment] 2021-06-03 09:15
Increase industry cost of tier 3 ark essense modules (they are currently same as tier 2)

**Comment by Mermixer** [comment] 2021-06-03 09:40
> Increase industry cost of tier 3 ark essense modules (they are currently same as tier 2)

i can get behind increased indy cost for this
ark modules all have the same cost (30)
the only one with an increasing one is the drain module, which goes from i believe 60 (t1) to 90 (t2/3)

**Comment by wakystuf** [comment] 2021-06-03 17:29
I am listing the T3 leeching module on the other thread, since that's more of a balancing calibration than an ESG bug

**Closed** 2021-06-07 17:18 UTC
Labels: esg bug, finished
