### ISSUE TITLE
Reduce the turn cost of System Development 3 & 4 to 1

### ISSUE THREAD

**Issue by Mermixer** [captaincobbs/ESG-Mod#439] opened 2021-04-14 08:33 UTC
You told me to do this but im like monkey and dont know how to use github @Doruk-Coskun

**Comment by captaincobbs** [comment] 2021-04-14 08:35
Reduce SD3/4 build times to 1 turn?

**Comment by Mermixer** [comment] 2021-04-14 08:35
how the fk do i do the assign thing

**Comment by Mermixer** [comment] 2021-04-14 08:35
yes

**Comment by wakystuf** [comment] 2021-04-14 15:47
This is a great idea. Would save a lot of micromanagement of the production queue overflows.

**Comment by Arpharnator** [comment] 2021-05-01 18:10
does anyone have a clue as to how to do this?

**Comment by wakystuf** [comment] 2021-05-01 18:22
I can probably do it. Not certain, but I think so. I think part of customcosts is the turn duration, which should be modifiable. I can probably try to look into that tomorrow; feel free to assign it to me and if I can't figure it out then I'll go crying to Cobbs asking for help.

**Comment by Arpharnator** [comment] 2021-05-01 18:24
the problem is that the turn cost is based on the luxury used, which is always one, and as such always gives 1, 2 and 3 turns for SD levels

**Comment by wakystuf** [comment] 2021-05-01 18:31
Hmmm...yeah that might be a problem; not sure quite how it works. I can try tomorrow, but that does make it less likely that I'll succeed

**Comment by wakystuf** [comment] 2021-05-01 19:49
2 ideas (with different pros and cons): 
1) Change all of those ingredient costs to 0.33. Pros: would round to 0 for SD2, and round to 1 for SD3-4. Cons: Might cause the game to explode
2) Set all of those values to 0. Pros: should work just fine, and won't really change industry costs (since overflow means they already don't "truly" cost industry anyway). Cons: Will make them go even faster than we'd wanted

**Comment by captaincobbs** [comment] 2021-05-03 00:37
It's not possible to reduce the turn cost of System Development, there's no constructible element definition for it anywhere, and my conclusion after researching this is that it's a programmatically created constructible that is generated after you choose your luxury.

**Comment by captaincobbs** [comment] 2021-05-03 00:38
Oh, I looked at what Arphar said, it is indeed based off of luxury. I'll do that now.

**Comment by captaincobbs** [comment] 2021-05-03 00:39
Ok, what arphar said is right, system development turn cost is based off of quantity of resources used, so we can't change that.

**Closed by captaincobbs** 2021-05-03 00:39 UTC
Labels: planned
