### ISSUE TITLE
ESG 1.6 - Starting Ships Cannot Explore Curiosities

### ISSUE THREAD

**Issue by AXEL-M74** [captaincobbs/ESG-Mod#1329] opened 2022-08-06 17:07 UTC
Pretty much title. 

The issue is only at the start. You need to de-equip and downgrade the ship, removing its modules and then upgrading it with the probe modules again to work.

I have no idea what causes these issues.

Only other mods I run are Black heroes and Grey Behemoths, cosmetic mods, besides ESG 1.6

![Screenshot_1](https://user-images.githubusercontent.com/105115857/183258838-abc17c14-2310-4558-9ecc-ff67b92570e8.png)
![Screenshot_2](https://user-images.githubusercontent.com/105115857/183258839-038c837f-aaac-437a-8af9-d04417f9e75c.png)

**Comment by wakystuf** [comment] 2022-08-06 18:53
What gamespeed is this?

**Comment by ghost** [comment] 2022-08-06 18:58
Here's the settings.

Normal speed.

![Screenshot_1](https://user-images.githubusercontent.com/105115857/183262528-90890c95-2d59-4b40-8146-3dd720d6e823.png)
![Screenshot_2](https://user-images.githubusercontent.com/105115857/183262530-ac813856-9116-4f77-9281-13f43b8e5703.png)
![Screenshot_3](https://user-images.githubusercontent.com/105115857/183262532-104b19e4-38da-4f1c-a1b1-a97f2e442648.png)
![Screenshot_4](https://user-images.githubusercontent.com/105115857/183262534-a82bf254-37bb-4b4a-b2b7-42a5b3cb0254.png)

**Comment by wakystuf** [comment] 2022-08-07 19:17
I see what the problem is here; should now be fixed with a change I just coded. Once I update Steam in a few days, let me know if this happens again.

**Closed as completed by wakystuf** 2022-08-07 19:17 UTC
Labels: Finished, Documented, ESG bug
